apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: -getway
  name: -getway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: -getway
      release: test
  template:
    metadata:
      labels:
        name: -getway
        release: test
    spec:
      containers:
      - name: -getway
        image: docker.ysd.com//getway:V14
        ports:
        - name: getway
          containerPort: 8765
        livenessProbe:
          httpGet:  
            port: 8765
            path: /info
          initialDelaySeconds: 500
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        #redis
        - name: REDIS_HOST
          value: "redis-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: 
        - name: REDIS_PASS
          value: ""
        #mysql
        - name: DB_HOST
          value: ""
        - name: DB_NAME
          value: ""
        - name: DB_USER
          value:
        - name: DB_PASS
          value: ""
        #mq
        - name: MQ_HOST
          value: ""
        - name: MQ_USER
          value: "admin"
        - name: MQ_PASS
          value: ""
        #eureka
        - name: SVC_NAME
          value: "socddp-eureka"
        - name: "REPL"
          value: "3"
        #mode_name
        - name: MODE_NAME
          value: "-gate"
---
apiVersion: v1
kind: Service 
metadata:
  labels:
    name: -getway
    release: test
  name: -getway
spec:
  type: NodePort
  ports:
  - name: -getway
    port: 8765
    targetPort: 8765
    nodePort: 30071 
  selector:
    name: -getway
    release: test
