apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: message
  name: message
spec:
  replicas: 1
  selector:
    matchLabels:
      name: message
      release: test
  template:
    metadata:
      labels:
        name: message
        release: test
    spec:
      containers:
      - name: message
        image: docker.ysd.com//socda-message:V2
        ports:
        - name: config
          containerPort: 8120
        #livenessProbe:
        #  httpGet:  
        #    port: 8120
        #    path: /info
        #  initialDelaySeconds: 240
        #  timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        #redis
        - name: REDIS_HOST
          value: "redis-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: 
        - name: REDIS_PASS
          value: ""
        #mysql
        - name: DB_HOST
          value: ""
        - name: DB_NAME
          value: ""
        - name: DB_USER
          value:
        - name: DB_PASS
          value: ""
        #mq
        - name: MQ_HOST
          value: ""
        - name: MQ_USER
          value: "admin"
        - name: MQ_PASS
          value: ""
        #eureka
        - name: SVC_NAME
          value: "socddp-eureka"
        - name: "REPL"
          value: "3"
        #mode_name
        - name: MODE_NAME
          value: "message"
---
apiVersion: v1
kind: Service 
metadata:
  labels:
    name: message
    release: test
  name: message
spec:
  ports:
  - name: message
    port: 8120
    targetPort: 8120
  selector:
    name: message
    release: test
