apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: -admin
  name: -admin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: -admin
      release: test
  template:
    metadata:
      labels:
        name: -admin
        release: test
    spec:
      containers:
      - name: -admin
        image: docker.ysd.com//-admin:V4
        ports:
        - name: config
          containerPort: 8762
        livenessProbe:
          httpGet:  
            port: 8762
            path: /info
          initialDelaySeconds: 120
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        #redis
        - name: REDIS_HOST
          value: "redis-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: 
        - name: REDIS_PASS
          value: ""
        #mysql
        - name: DB_HOST
          value: ""
        - name: DB_NAME
          value: ""
        - name: DB_USER
          value:
        - name: DB_PASS
          value: ""
        #mq
        - name: MQ_HOST
          value: ""
        - name: MQ_USER
          value: "admin"
        - name: MQ_PASS
          value: ""
        #eureka
        - name: SVC_NAME
          value: "socddp-eureka"
        - name: "REPL"
          value: "3"
        #mode_name
        - name: MODE_NAME
          value: "-admin"
---
apiVersion: v1
kind: Service 
metadata:
  labels:
    name: -admin
    release: test
  name: -admin
spec:
  ports:
  - name: -admin
    port: 8762
    targetPort: 8762
  selector:
    name: -admin
    release: test
