apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: -auth
  name: -auth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: -auth
      release: test
  template:
    metadata:
      labels:
        name: -auth
        release: test
    spec:
      containers:
      - name: -auth
        image: docker.ysd.com//-auth:V3
        ports:
        - name: config
          containerPort: 5672
        livenessProbe:
          httpGet:  
            port: 5672
            path: /info
          initialDelaySeconds: 100
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        #redis
        - name: REDIS_HOST
          value: "redis-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: 
        - name: REDIS_PASS
          value: ""
        #mysql
        - name: DB_HOST
          value: ""
        - name: DB_NAME
          value: ""
        - name: DB_USER
          value:
        - name: DB_PASS
          value: ""
        #mq
        - name: MQ_HOST
          value: ""
        - name: MQ_USER
          value: "admin"
        - name: MQ_PASS
          value: ""
        #eureka
        - name: SVC_NAME
          value: "socddp-eureka"
        - name: "REPL"
          value: "3"
        #mode_name
        - name: MODE_NAME
          value: "-auth"
---
apiVersion: v1
kind: Service 
metadata:
  labels:
    name: -auth
    release: test
  name: -auth
spec:
  ports:
  - name: -auth
    port: 5672
    targetPort: 5672
  selector:
    name: -auth
    release: test
